### ISSUE TITLE
CUBLAS_STATUS_INTERNAL_ERROR when calling cublasLtMatmul

### ISSUE THREAD

**Issue by dokipen3d** [UniLat3D/UniLat3D#5]
Getting this error when running the gradio demo locally...

`Error during processing: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling cublasLtMatmul with transpose_mat1 1 transpose_mat2 0 m 5120 n 4096 k 1280 mat1_ld 1280 mat2_ld 1280 result_ld 5120 abcType 2 computeType 68 scaleType 0`

**Comment by dokipen3d** [comment]
I recreated the python 3.10 environment to match the one I found on huggingface (the requirements.txt is not in this repo) with cuda 12.4.


unfortunately, the error message is still the same...

```

2025-11-07 16:07:06.0503619 [E:onnxruntime:Default, provider_bridge_ort.cc:1848 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\TechArtPC\Documents\ProjectsLocal\UniLat3D\env1\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:507 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
C:\Users\TechArtPC\Documents\ProjectsLocal\UniLat3D\external/dinov3\dinov3\layers\attention.py:116: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  x = torch.nn.functional.scaled_dot_product_attention(q, k, v)
Sampling:   0%|                                                                                                                              | 0/50 [00:00<?, ?it/s]
❌ Error during processing: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling cublasLtMatmul with transpose_mat1 1 transpose_mat2 0 m 5120 n 4096 k 1280 mat1_ld 1280 mat2_ld 1280 result_ld 5120 abcType 2 computeType 68 scaleType 0
```
Here is the windows requirements.txt for anyone interested with the windows wheels grabbed from the trellis project.

```
--extra-index-url https://download.pytorch.org/whl/cu124

torch==2.4.0
torchvision==0.19.0
pillow==10.4.0
imageio==2.36.1
imageio-ffmpeg==0.5.1
tqdm==4.67.1
easydict==1.13
opencv-python-headless==4.10.0.84
scipy==1.14.1
rembg[gpu]==2.0.60
onnxruntime-gpu==1.20.1
trimesh==4.5.3
xatlas==0.0.9
pyvista==0.44.2
pymeshfix==0.17.0
igraph==0.11.8
git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8
xformers==0.0.27.post2
spconv-cu124
transformers==4.46.3
gradio_litmodel3d==0.0.1
pydantic==2.10.6
numpy==1.26.3
torchmetrics
# https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.0.post2/flash_attn-2.7.0.post2+cu12torch2.4cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
# https://huggingface.co/spaces/JeffreyXiang/TRELLIS/resolve/main/wheels/diff_gaussian_rasterization-0.0.0-cp310-cp310-linux_x86_64.whl?download=true
# https://huggingface.co/spaces/JeffreyXiang/TRELLIS/resolve/main/wheels/nvdiffrast-0.3.3-cp310-cp310-linux_x86_64.whl?download=true
https://github.com/kingbri1/flash-attention/releases/download/v2.7.0.post2/flash_attn-2.7.0.post2+cu124torch2.4.0cxx11abiFALSE-cp310-cp310-win_amd64.whl
https://github.com/sdbds/diff-gaussian-rasterization/releases/download/diff-gaussian-rasterization/diff_gaussian_rasterization-0.0.0-cp310-cp310-win_amd64.whl
https://github.com/sdbds/TRELLIS-for-windows/releases/download/nvdiffrast-0.3.3/nvdiffrast-0.3.3-py3-none-any.whl
```

**Comment by dokipen3d** [comment]
I have it working now. thanks (also multiview results look promising)

I used this wheel instead of the one I previously posted...

https://huggingface.co/lldacing/flash-attention-windows-wheel/blob/main/flash_attn-2.7.0.post2%2Bcu124torch2.4.0cxx11abiFALSE-cp310-cp310-win_amd64.whl
